[package]
name = "wimux-client"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
wimux-protocol.workspace = true
wimux-vt.workspace = true
thiserror.workspace = true
crossterm = "0.29.0"
windows = { version = "0.62.2", features = ["Win32_Foundation", "Win32_System_Console"] }
