[package]
name = "wimux-server"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "wimux-server"
path = "src/main.rs"

[dependencies]
wimux-protocol.workspace = true
wimux-vt.workspace = true
thiserror.workspace = true
portable-pty = "0.9.0"
anyhow = "1.0.103"
chromiumoxide = "0.9.1"
tokio = { version = "1.53.1", features = ["rt-multi-thread", "macros", "sync", "time"] }
futures = "0.3.33"
